services: 
  # This service is used to build the static files for the site. It mounts the current directory and the output directory, runs the build command, and then copies the built files to the output directory.
  builder:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - ../site:/out
    command: >
     sh -lc "npm ci && npm run build && rm -rf /out/* && cp -a dist/. /out/"
    profiles: ["build"]    
  # Runtime (nginx) service that serves the built static files. It mounts the output directory to the nginx html directory and exposes port 8086.
  web:
    image: nginx:alpine
    container_name: crowdfunding-product-page
    ports:
      - "8086:80"
    volumes:
      - ../site:/usr/share/nginx/html:ro
    restart: unless-stopped